
var oTo_CSS_modele = new Object();
oTo_CSS_modele['properties'] = new Object();

var css_oto_modele_properties = document.createElement('script');
css_oto_modele_properties.type = 'text/javascript';
css_oto_modele_properties.src = 'CSS_oTo_modele_properties.js';
document.head.appendChild(css_oto_modele_properties) ;


oTo_CSS_modele['properties_type_fr'] = new Array( 'textes', ' listes', ' couleurs et fonds', ' boites', ' tableaux', ' positions et affichages', ' animations', 'autres');
oTo_CSS_modele['properties_type_en'] = new Array( 'texts', ' lists', ' colors and backgrounds', ' boxes', ' tables', ' positions et displays', ' animations', 'others');

oTo_CSS_modele['properties_type'] = new Object ();

oTo_CSS_modele['properties_type']['texts'] = new Array (
'font-family', 
'font-size', 
'font-weight', 
'font-style', 
'text-decoration', 
'font-variant', 
'font', 
'@font-face', 
'',
'line-height', 
'',
'text-transform', 
'text-indent', 
'text-align', 
'vertical-align', 
'',
'white-space', 
'word-wrap', 
'word-spacing', 
'word-break', 
'',
'(css3)',
'font-size-adjust', 
'font-stretch', 
'',
'text-shadow', 
'text-justify', 
'text-outline', 
'text-overflow', 
'text-wrap', 
'',
'letter-spacing', 
'quotes'
);

oTo_CSS_modele['properties_type']['lists'] = new Array (
'list-style-type', 
'list-style-position', 
'list-style-image', 
'list-style',
'',
'(css3)',
'counter-increment', 
'counter-reset'
);

oTo_CSS_modele['properties_type']['colors_Images_and_backgrounds'] = new Array (
'color', 
'opacity', 
'',
'background-color', 
'background-image', 
'background-attachment', 
'background-repeat', 
'background-position', 
'background', 
'',
'(css3)',
'background-clip', 
'background-origin', 
'background-size', 
'',
'icon'
);

oTo_CSS_modele['properties_type']['boxes'] = new Array (
'width', 
'height', 
'min-width', 
'max-width', 
'min-height', 
'max-height', 
'',
'margin', 
'margin-top', 
'margin-right', 
'margin-bottom', 
'margin-left', 
'',
'padding', 
'padding-top', 
'padding-right', 
'padding-bottom', 
'padding-left', 
'',
'border', 
'border-top', 
'border-right', 
'border-bottom', 
'border-left', 
'border-width', 
'border-color', 
'border-style', 
'border-top-width', 
'border-top-color', 
'border-top-style', 
'border-right-width', 
'border-right-color', 
'border-right-style', 
'border-bottom-width', 
'border-bottom-color', 
'border-bottom-style', 
'border-left-width', 
'border-left-color', 
'border-left-style', 
'',
'(css3)',
'border-radius', 
'border-bottom-left-radius', 
'border-bottom-right-radius', 
'border-image', 
'border-image-outset', 
'border-image-repeat', 
'border-image-slice', 
'border-image-source', 
'border-image-width', 
'border-top-left-radius', 
'border-top-right-radius', 
'',
'outline', 
'outline-color', 
'outline-offset', 
'outline-style', 
'outline-width', 
'',
'border-spacing', 
'box-shadow', 
'box-align', 
'box-direction', 
'box-flex', 
'box-flex-group', 
'box-lines', 
'box-ordinal-group', 
'box-orient', 
'box-pack', 
'box-sizing', 
'',
'columns', 
'column-count', 
'column-fill', 
'column-gap', 
'column-rule', 
'column-rule-color', 
'column-rule-style', 
'column-rule-width', 
'column-span', 
'column-width', 
'',
'grid-columns', 
'grid-rows', 
'',
'resize', 
'rotation', 
'rotation-point', 
'',
'transform', 
'transform-origin', 
'transform-style', 
'',
'hanging-punctuation', 
'punctuation-trim'
);

oTo_CSS_modele['properties_type']['tables'] = new Array (
'border-collapse', 
'empty-cells', 
'caption-side', 
'table-layout'
);

oTo_CSS_modele['properties_type']['positions_and_displays'] = new Array (
'position', 
'display', 
'float', 
'clear', 
'',
'top', 
'bottom', 
'left', 
'right', 
'z-index', 
'',
'overflow', 
'overflow-x', 
'overflow-y', 
'',
'direction', 
'visibility', 
'clip', 
'',
'(css3)',
'page-break-after', 
'page-break-before', 
'page-break-inside', 
'',
'perspective', 
'perspective-origin'
);

oTo_CSS_modele['properties_type']['animations'] = new Array (
'',
'(css3)',
'@keyframes', 
'animation', 
'animation-name', 
'animation-duration', 
'animation-timing-function', 
'animation-delay', 
'animation-iteration-count', 
'animation-direction', 
'animation-play-state', 
'',
'transition', 
'transition-property', 
'transition-duration', 
'transition-timing-function', 
'transition-delay' 
);

oTo_CSS_modele['properties_type']['other'] = new Array (
'cursor', 
'',
'(css3)',
'appearance', 
'backface-visibility', 
'content', 
'',
'nav-down', 
'nav-index', 
'nav-left', 
'nav-right', 
'nav-up', 
'',
'target', 
'target-name', 
'target-new', 
'target-position'
);

// alert (oTo_CSS_modele['properties_type']['texts'].join(' - '));
// alert (oTo_CSS_modele['properties']['border']['explain_values_en']);
